#!/bin/bash
# core/scripts/context-pack.sh — Generate pre-bundled context for a builder agent
# Usage: ./core/scripts/context-pack.sh <codename>
# Output: metrics/context-<codename>.md
#
# Reads the task's "touches" column from sequence.md and bundles relevant
# file excerpts into a single markdown file. This saves the builder from
# spending context on file discovery.
#
# Key files are discovered from factory/profile.yaml's context_pack section.
# The context pack is READ-ONLY — the builder should not modify it.
# Total size is capped at ~4K chars to avoid bloating the prompt.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "${SCRIPT_DIR}/lib.sh"

CODENAME="${1:-}"
if [ -z "${CODENAME}" ]; then
    echo "Usage: ./core/scripts/context-pack.sh <codename>"
    exit 1
fi

# ── Resolve phase and touches ──
PHASE_NUM=""
if is_codename "${CODENAME}"; then
    PHASE_NUM=$(resolve_phase "${CODENAME}") || {
        echo "  context-pack: codename '${CODENAME}' not found"
        exit 1
    }
else
    PHASE_NUM="${CODENAME%%.*}"
fi

TOUCHES=$(task_touches "${CODENAME}" "${PHASE_NUM}")
SPEC_FILE=$(resolve_spec "${CODENAME}" "${PHASE_NUM}")

OUTPUT="metrics/context-${CODENAME}.md"
mkdir -p metrics

# ── Helper: append file excerpt with header and timestamp ──
append_excerpt() {
    local FILE="$1"
    local LABEL="$2"
    local LINES="${3:-50}"

    if [ ! -f "${FILE}" ]; then
        return
    fi

    local MOD_TIME
    MOD_TIME=$(stat -f "%Sm" -t "%Y-%m-%d %H:%M" "${FILE}" 2>/dev/null \
        || stat -c "%y" "${FILE}" 2>/dev/null | cut -d. -f1 \
        || echo "unknown")

    {
        echo ""
        echo "## ${LABEL}"
        echo "_File: ${FILE} | Modified: ${MOD_TIME}_"
        echo '```'
        head -n "${LINES}" "${FILE}"
        echo '```'
    } >> "${OUTPUT}"
}

# ── Helper: append excerpt matching a pattern ──
append_filtered() {
    local FILE="$1"
    local LABEL="$2"
    local PATTERN="$3"
    local CONTEXT="${4:-2}"

    if [ ! -f "${FILE}" ]; then
        return
    fi

    local MATCHES
    MATCHES=$(grep -n -A "${CONTEXT}" "${PATTERN}" "${FILE}" 2>/dev/null | head -60)
    if [ -z "${MATCHES}" ]; then
        return
    fi

    {
        echo ""
        echo "## ${LABEL}"
        echo "_File: ${FILE}_"
        echo '```'
        echo "${MATCHES}"
        echo '```'
    } >> "${OUTPUT}"
}

# ── Start the context file ──
{
    echo "# Context Package for Task: ${CODENAME}"
    echo "_Auto-generated by context-pack.sh — DO NOT EDIT_"
    echo "_Touches: ${TOUCHES}_"
    echo ""
    echo "> Read this file ONCE. Do NOT re-read the individual files excerpted below."
} > "${OUTPUT}"

# ── Include files based on profile.yaml context_pack config ──
# Format in profile.yaml:
#   context_pack:
#     all:
#       - path: src/db/schema.rs
#         label: DB Schema
#         lines: 40
#     backend:
#       - path: src/lib.rs
#         label: Backend Entry
#     frontend:
#       - path: src/types.ts
#         label: Shared Types
if [ -f "factory/profile.yaml" ]; then
    # Determine which sections to include based on touches
    SECTIONS="all"
    if echo "${TOUCHES}" | grep -q "all\|shared"; then
        # Read all sections from profile
        SECTIONS=$(sed -n '/^context_pack:/,/^[a-z]/{
            /^[[:space:]]*[a-z]/p
        }' factory/profile.yaml 2>/dev/null \
            | sed 's/:.*//' | tr -d ' ' | grep -v '^$')
        [ -z "${SECTIONS}" ] && SECTIONS="all"
    else
        SECTIONS="all ${TOUCHES//,/ }"
    fi

    for SECTION in ${SECTIONS}; do
        # Extract file entries for this section
        IN_SECTION=""
        while IFS= read -r line; do
            if echo "$line" | grep -qE "^[[:space:]]*${SECTION}:"; then
                IN_SECTION="1"
                continue
            fi
            if [ -n "${IN_SECTION}" ]; then
                if echo "$line" | grep -qE "^[[:space:]]*[a-z]+:" && ! echo "$line" | grep -qE "^[[:space:]]*(path|label|lines|pattern):"; then
                    break
                fi
                if echo "$line" | grep -qE "^[[:space:]]*- path:"; then
                    local_path=$(echo "$line" | sed 's/.*path:[[:space:]]*//')
                    local_label=""
                    local_lines="50"
                elif echo "$line" | grep -qE "^[[:space:]]*label:"; then
                    local_label=$(echo "$line" | sed 's/.*label:[[:space:]]*//')
                elif echo "$line" | grep -qE "^[[:space:]]*lines:"; then
                    local_lines=$(echo "$line" | sed 's/.*lines:[[:space:]]*//')
                    # Emit the entry
                    [ -z "${local_label}" ] && local_label=$(basename "${local_path}")
                    append_excerpt "${local_path}" "${local_label}" "${local_lines}"
                fi
            fi
        done < factory/profile.yaml
    done
else
    # No profile — auto-discover key files
    while IFS= read -r f; do
        [ -f "$f" ] && append_excerpt "$f" "$(basename "$f")" 40
    done < <(find . -maxdepth 4 -type f \( \
        -name "schema.rs" -o -name "schema.prisma" -o -name "schema.py" \
        -o -name "types.ts" -o -name "models.py" -o -name "lib.rs" \
    \) -not -path '*/node_modules/*' -not -path '*/target/*' 2>/dev/null | head -10)
fi

# ── Extract file paths from the task spec ──
if [ -n "${SPEC_FILE}" ] && [ -f "${SPEC_FILE}" ]; then
    REFERENCED_FILES=$(grep -oE '[a-zA-Z0-9_.-]+/[a-zA-Z0-9_./-]+\.[a-zA-Z]+' "${SPEC_FILE}" 2>/dev/null \
        | sort -u | head -10)

    if [ -n "${REFERENCED_FILES}" ]; then
        {
            echo ""
            echo "## Files Referenced in Task Spec"
            echo "_These files are mentioned in the task spec — check if they exist before reading._"
            echo ""
        } >> "${OUTPUT}"

        for REF_FILE in ${REFERENCED_FILES}; do
            if [ -f "${REF_FILE}" ]; then
                echo "- \`${REF_FILE}\` (exists)" >> "${OUTPUT}"
            else
                echo "- \`${REF_FILE}\` (does not exist yet)" >> "${OUTPUT}"
            fi
        done
    fi
fi

# ── Size check: warn if over 4K ──
FINAL_SIZE=$(wc -c < "${OUTPUT}" | tr -d ' ')
if [ "${FINAL_SIZE}" -gt 4096 ]; then
    echo "  context-pack: warning — ${OUTPUT} is ${FINAL_SIZE} bytes (target: <4096)"
    TRUNCATED=$(head -n 120 "${OUTPUT}")
    {
        echo "${TRUNCATED}"
        echo ""
        echo "_[Truncated to stay under 4K chars]_"
    } > "${OUTPUT}"
    FINAL_SIZE=$(wc -c < "${OUTPUT}" | tr -d ' ')
fi

echo "  context-pack: ${OUTPUT} (${FINAL_SIZE} bytes, touches: ${TOUCHES})"
